services:
  tmp-files-blue:
    image: ghcr.io/andywijaya15/tmp-files:latest
    container_name: tmp-files-blue
    volumes:
      - ./tmp:/app/tmp
      - ./static:/app/static
    ports:
      - "${PORT1}:3003"
    restart: unless-stopped
  tmp-files-green:
    image: ghcr.io/andywijaya15/tmp-files:latest
    container_name: tmp-files-green
    volumes:
      - ./tmp:/app/tmp
      - ./static:/app/static
    ports:
      - "${PORT2}:3003"
    restart: unless-stopped
